# Generated by Django 3.2.5 on 2022-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcc_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog_contents',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
