# Generated by Django 3.2.5 on 2022-04-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcc_home', '0001_squashed_squashed_0003_home_contents_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='PG_contents',
            new_name='Programming_contents',
        ),
        migrations.AlterField(
            model_name='home_contents',
            name='icon',
            field=models.CharField(max_length=200),
        ),
    ]
