# Generated by Django 3.2.5 on 2022-04-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcc_home', '0001_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_contents',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
